-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Musteriler"
(
    "Id" integer,
    "MusteriNo" character varying(25),
    "KanalId" integer,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Adresler"
(
    "Id" integer,
    "AdresDetay" character varying(250),
    "MusteriId" integer,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Bilancolar"
(
    "Id" integer,
    "Tarih" date,
    "Tutar" money,
    "MusteriId" integer,
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."GercekMusteriler"
(
    "MusteriId" integer,
    "Ad" character varying(20),
    "Soyad" character varying(20),
    "TcKimlikNo" character varying(11),
    PRIMARY KEY ("MusteriId")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."TicariFaaliyetler"
(
    "MusteriId" integer,
    "GercekMusteriId" integer,
    "BaslangicTarihi" date,
    PRIMARY KEY ("MusteriId")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Sendikalar"
(
    "MusteriId" integer,
    "Ad" character varying(30),
    PRIMARY KEY ("MusteriId")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."Kanallar"
(
    "Id" integer,
    "Ad" character varying(30),
    PRIMARY KEY ("Id")
)
WITH (
    OIDS = FALSE
);

CREATE TABLE public."TuzelMusteriler"
(
    "MusteriId" integer,
    "Unvan" character varying(20),
    "VergiNo" character varying(10),
    PRIMARY KEY ("MusteriId")
)
WITH (
    OIDS = FALSE
);

ALTER TABLE public."Musteriler"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."GercekMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Musteriler"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Sendikalar" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Musteriler"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."TicariFaaliyetler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Musteriler"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."TuzelMusteriler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Kanallar"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Musteriler" ("KanalId")
    NOT VALID;


ALTER TABLE public."Musteriler"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Adresler" ("MusteriId")
    NOT VALID;


ALTER TABLE public."Musteriler"
    ADD FOREIGN KEY ("Id")
    REFERENCES public."Bilancolar" ("MusteriId")
    NOT VALID;

END;
